# MIT License
# Copyright (C) 2020 Tymko Oleg <olegtymko@yandex.ru> and contributors
# All rights reserved.

name: Контроль качества
# Любой пуш и pr в проекте но с фильтром по основному проекту
on: [push, pull_request]

env:
  # отключение безопасности установки, от 2020-10-01
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    if: github.repository == 'arkuznetsov/nextcloud-lib'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        oscript_version: ['1.7.0']

    steps:
      # Загрузка проекта
      - name: Актуализация
        uses: actions/checkout@v2
        with:
          # Disabling shadow clone is recomended
          fetch-depth: 0

      # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
      - name: Извлечение имени текущей ветки
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # Установка OneScript конкретной версии
      - name: Установка OneScript
        uses: otymko/setup-onescript@v1.1
        with:
          version: ${{ matrix.oscript_version }}

      # Установка зависимостей пакета
      - name: Установка зависимостей
        run: |
          opm install opm
          opm install --dev

      # Запуск контейнера NextCloud
      - name: Запуск контейнера NextCloud
        env:
          NC_ADMIN_NAME: ${{ secrets.NC_ADMIN_NAME }}
          NC_ADMIN_PWD: ${{ secrets.NC_ADMIN_PWD }}
        run: |
          docker run --name nextcloud -d -p 8080:80 nextcloud
          docker ps
          while [ "`curl -I -L -s http://localhost:8080 | grep "HTTP/1.1" | grep -oE '\b[0-9]{3}\b'`" != "200" ]; do docker ps && sleep 2; done
          docker ps
          docker exec --user www-data nextcloud php occ maintenance:install --admin-user ${NC_ADMIN_NAME} --admin-pass ${NC_ADMIN_PWD}

      # Запуск тестов и сбор покрытия кода
      - name: Тестирование и расчет покрытия кода
        env:
          NC_ADMIN_NAME: ${{ secrets.NC_ADMIN_NAME }}
          NC_ADMIN_PWD: ${{ secrets.NC_ADMIN_PWD }}
        run: oscript ./tasks/coverage.os

      - name: Извлечение версии пакета
        shell: bash
        run: echo "##[set-output name=version;]`cat packagedef | grep ".Версия(" | sed 's|[^"]*"||' | sed -r 's/".+//'`"
        id: extract_version

      - name: Установка Sonar-scanner
        uses: warchant/setup-sonar-scanner@v1

      # Анализ проекта в SonarQube (ветка)
      - name: Анализ в SonarQube (branch)
        if: github.event_name == 'push'
        run: sonar-scanner
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
            -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}
            -Dsonar.projectVersion=${{ steps.extract_version.outputs.version }}

      # Анализ проекта в SonarQube (PR)
      # https://docs.sonarqube.org/latest/analysis/pull-request/
      - name: Анализ в SonarQube (pull-request)
        if: github.event_name == 'pull_request'
        run: sonar-scanner
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
            -Dsonar.host.url=${{ secrets.SONARQUBE_HOST }}
            -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
            -Dsonar.scm.revision=${{ github.event.pull_request.head.sha }}
